const xml=(value='')=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
function lines(text,max=28,limit=4){const chars=[...String(text||'').trim()],out=[];while(chars.length&&out.length<limit)out.push(chars.splice(0,max).join(''));return out}
function tspans(items,x,y,step){return items.map((line,i)=>`<tspan x="${x}" y="${y+i*step}">${xml(line)}</tspan>`).join('')}
export function buildVisualAssets({title,description,category,tags=[],sections=[]}){
  const titleLines=lines(title,24,3),descLines=lines(description,42,3);
  const cover=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630" role="img" aria-labelledby="t d"><title id="t">${xml(title)}</title><desc id="d">${xml(description)}</desc><rect width="1200" height="630" rx="32" fill="#0b0b0b"/><circle cx="1040" cy="110" r="190" fill="#202020"/><circle cx="1050" cy="120" r="110" fill="#3a3a3a"/><rect x="72" y="62" width="260" height="48" rx="24" fill="#f5f5f3"/><text x="94" y="94" font-family="system-ui,sans-serif" font-size="22" font-weight="750" fill="#111111">${xml(category||'AI 자동화')}</text><text font-family="system-ui,sans-serif" font-weight="800" font-size="58" fill="#ffffff">${tspans(titleLines,72,185,72)}</text><text font-family="system-ui,sans-serif" font-size="25" fill="#d6d6d3">${tspans(descLines,72,430,36)}</text><text x="72" y="575" font-family="system-ui,sans-serif" font-size="22" fill="#a7a7a3">${xml(tags.slice(0,4).map(t=>`#${t}`).join('  '))}</text></svg>`;
  const takeaways=sections.slice(0,4).map((section,i)=>({n:String(i+1).padStart(2,'0'),heading:section.heading,detail:(section.bullets?.[0]||section.paragraphs?.[0]||'').slice(0,90)}));
  const cards=takeaways.map((item,i)=>{const y=150+i*150;return `<rect x="60" y="${y}" width="1080" height="120" rx="20" fill="#ffffff" stroke="#d9d9d6"/><rect x="86" y="${y+24}" width="48" height="48" rx="14" fill="#111111"/><text x="100" y="${y+57}" font-family="system-ui,sans-serif" font-size="18" font-weight="800" fill="#ffffff">${item.n}</text><text x="158" y="${y+43}" font-family="system-ui,sans-serif" font-size="26" font-weight="800" fill="#111111">${xml(lines(item.heading,32,1)[0]||'')}</text><text x="158" y="${y+82}" font-family="system-ui,sans-serif" font-size="20" fill="#555555">${xml(lines(item.detail,58,1)[0]||'')}</text>`}).join('');
  const summary=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="780" viewBox="0 0 1200 780" role="img" aria-labelledby="t2"><title id="t2">${xml(title)} 핵심 요약</title><rect width="1200" height="780" rx="28" fill="#f7f7f5"/><text x="60" y="72" font-family="system-ui,sans-serif" font-size="34" font-weight="850" fill="#111111">핵심 요약</text><text x="60" y="112" font-family="system-ui,sans-serif" font-size="19" fill="#666666">본문의 검증된 내용을 빠르게 훑기 위한 자동 생성 인포그래픽</text>${cards}<text x="60" y="748" font-family="system-ui,sans-serif" font-size="16" fill="#8a8a86">Practical AI &amp; Automation · final fact-checked article</text></svg>`;
  return{cover,summary};
}
